name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  reactive_forms_json_scheme:
    path: ../
  mask_text_input_formatter: ^2.9.0
  reactive_date_range_picker: ^2.3.0
  reactive_date_time_picker: ^5.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
